# Site settings
title: Jekyll Styleguide
email: info@folklabs.com
description: > # this means to ignore newlines until "baseurl:"
  Jekyll styleguide template by Folk Labs.
baseurl: "/jekyll-styleguide" # the subpath of your site, e.g. /blog/
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: folklabs
github_username:  folklabs

# Build settings
markdown: kramdown

collections:
  patterns:
    output: true
  atoms:
    output: true
